name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  push:
  schedule:
    - cron:  '*/5 * * * *'
env:
  GH_TOKEN: ${{ github.token }}
jobs:
  Get-Previous-Run-Info:
    runs-on: ubuntu-latest
    outputs:
        json: ${{ steps.get-json.outputs.result }}
        updated: ${{ steps.get-json.outputs.updated }}
    steps:
      - name: 'check commit sha with the prev succeeded workflow run'
        id: 'get-json'
        run: |
          result=$(gh api -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28"  "/repos/${{ github.repository }}/actions/runs?status=success&branch=main&per_page=1")
          echo "result=${result}" >> $GITHUB_OUTPUT
          head_sha=`echo ${result} | jq '.workflow_runs[0].head_sha'`
          updated=$(if [ ${head_sha} = ${{ github.sha }} ]; then echo 'false'; else echo "true"; fi;)
          echo "updated=${updated}" >> $GITHUB_OUTPUT
          echo "previous workflow info summary"
          echo ${result} | jq '.workflow_runs[] | {id: .id, branch:.head_branch, sha:.head_sha, run_number:.run_number, updated_at:.updated_at}'
          echo "this workflow commit sha"
          echo ${{ github.sha }} 
  Job-With-New-Commit:
    runs-on: ubuntu-latest
    needs:
      - Get-Previous-Run-Info
    if: fromJson(needs.Get-Previous-Run-Info.outputs.updated)
    steps:
      - id: your-step
        run: | 
          echo "this commit is not same with the previous succeeded workflow run."
          echo "${{ fromJson(needs.Get-Previous-Run-Info.outputs.updated) }}"

  Job-With-Same-Commit:
    runs-on: ubuntu-latest
    needs:
      - Get-Previous-Run-Info
    if: fromJson(needs.Get-Previous-Run-Info.outputs.updated) != true
    steps:
      - id: your-step
        run: |
          echo "this commit is same with the previous succeeded workflow run."
          echo "${{ fromJson(needs.Get-Previous-Run-Info.outputs.updated) }}"

      